config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :buses
  root 'buses#index'
end

app/models/bus.rb
class Bus < ActiveRecord::Base

    has_many :photos, dependent: :destroy

    #accepts_nested_attributes_for :photos

    validates :name, presence: true
    validates :number, uniqueness: { case_sensitive: false }
    validates :pts, presence: true
    validates :pts_date, presence: true

     validates_with BusNumberValidator, fields: [:number]

    def self.valid_letters_in_number
        ['А', 'В', 'Е', 'К', 'М', 'Н', 'О', 'Р', 'С', 'Т', 'У', 'Х']
    end

    def description
        return "##{id} #{name} #{number}"
    end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bus

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
require 'unicode'

class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
    if Rails.env = "development"
      @bus.name = "Автобус_" + (65 + rand(26)).chr + rand(100).to_s
      @bus.pts = "ПТС_" + (65 + rand(26)).chr + rand(100).to_s
      valid_letters = Bus.valid_letters_in_number
      @bus.number = valid_letters[rand(12)] + rand(10).to_s + rand(10).to_s + rand(10).to_s + 
        (0..1).map{ valid_letters[rand(12)] }.join + rand(10).to_s + rand(10).to_s
    end
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save        
        save_photos
        format.html { redirect_to buses_path, notice: "Создано: #{@bus.description}" }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        save_photos
        format.html { redirect_to buses_path, notice: "Обновлено: #{@bus.description}" }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: "Удалено: #{@bus.description}" }
      format.json { head :no_content }
    end
  end

  private
def save_photos
  if not params[:photos].nil?
    params[:photos]['image'].each do |i|
      @bus.photos.create!(:image => i)
    end
  end
end

    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      h = params.require(:bus).permit(:name, :number, :pts, :pts_date)
      h[:number] = Unicode::upcase(h[:number])
      return h
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    if not params[:bus_id].nil?
      @photo.bus = Bus.find(params[:bus_id])
    end
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    bus_id = @photo.bus_id
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to edit_bus_path(bus_id), notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :image, :bus_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_number_validator.rb
class BusNumberValidator < ActiveModel::Validator
  def validate(bus)
    error = false

    l = bus.number.length
    error = l < 8 or l > 9        

    if not error
        valid_letters = Bus.valid_letters_in_number
        valid_digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

        s = bus.number
        digits = s[1..3] + s[6..-1]
        letters = s[0] + s[4..5]

        error = check(digits, valid_digits) or check(letters, valid_letters)
    end

    if error
        bus.errors[:base] << "Номер должен быть в формате А000АА00 или А000АА000"
    end        
  end

  private

  def check(s, arr)
    error = false
    s.each_char do |ch|
        if not arr.include?(ch)
            error = true;
        end
    end

    return error
  end

end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/buses/_form.html.erb
<%= form_for(@bus, :html => { :multipart => true }) do |f| %>
<% if @bus.errors.any? %>
<div id="error_explanation">
  <h2>Невозможно сохранить</h2>

  <ul>
    <% @bus.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <div class="hblock">
    <div class="field">
      <%= f.label "Наименование" %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label "Гос номер" %><br>
      <%= f.text_field :number %>
    </div>
  </div>
  <div class="hblock">
    <div class="field">
      <%= f.label "ПТС" %><br>
      <%= f.text_field :pts %>
    </div>
    <div class="field">
      <%= f.label "Дата ПТС" %><br>
      <%= f.date_select :pts_date %>
    </div>
  </div>
  <div class="clear"></div>
</div>


<%= f.fields_for([ @bus, @bus.photos.build ]) do |p| %>
<div class="field">
  <%= f.label "Фотографии" %><br>
  <%= p.file_field :image, :multiple => true, name: "photos[image][]" %>
</div>
<% end %>

<div class="actions">
  <%= f.submit "Сохранить" %>
</div>
<% end %>

app/views/buses/edit.html.erb
<h1>Редактирование</h1>

<%= render 'form' %>

<div id="photos">
    <% for photo in @bus.photos %>
        <% if photo.id %>
            <div class="photo">
                <a href="<%= photo.image_url %>">
                    <%= image_tag photo.image_url(:thumb) if photo.image? %>        
                </a>
                <div class="actions">
                    <%= link_to 'Удалить', photo, method: :delete, data: { confirm: 'Вы уверены?' } %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/buses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список автобусов</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Наименование</th>
        <th>Гос. номер</th>
        <th>ПТС</th>
        <th>Дата ПТС</th>
        <th>Фото</th>
        <th><%= link_to 'Новый', new_bus_path, :class => "btn btn-primary" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @buses.each do |bus| %>
        <tr>
          <td><%= bus.id %></td>
          <td><%= bus.name %></td>
          <td><%= bus.number %></td>
          <td><%= bus.pts %></td>
          <td><%= bus.pts_date %></td>
          <td><%= "\u2713" if bus.photos.count > 0 %></td>
          <td><%= link_to 'Редактировать', edit_bus_path(bus), :class => "btn btn-info" %></td>
          <td><%= link_to 'Удалить', bus, method: :delete, data: { confirm: 'Вы уверены?' }, :class => "btn btn-danger" %></td>
        </tr>
      <% end %>      
    </tbody>
  </table>
  <p>
        <td>Всего: <%= Bus.count %></td>
    </p>
</div>

app/views/buses/new.html.erb
<h1>Новый автобус</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Busfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
        <strong><%= link_to 'Домой', root_path %></strong>
        <hr>
        <%= yield %>
    </div>
</body>
</html>